name: JAVA CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  check-skip:
    name: ✋ Cancel Previous Redundant Builds
    runs-on: ubuntu-20.04
    steps:
      - name: ✋ Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  checkstyle:
    name: 🚨 Checkstyle
    runs-on: ubuntu-20.04
    steps:
      - name: 🚨 Checkstyle
        uses: actions/checkout@v2
      - name: 🚨 Checkstyle
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 🚨 Checkstyle
        run: mvn validate -f pom.xml